### ISSUE TITLE
Mass migration

### ISSUE THREAD

**Issue by priyanshu-singhania** [aniyomiorg/aniyomi#1594] opened 2024-06-02 01:59 UTC
### Describe your suggested feature

Migrate all(or multiple) animes/mangas from one source to another just like in TachiyomiSY.

### Other details

This feature is available in TachiyomiSY.
https://github.com/jobobby04/tachiyomisy

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.3.0](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by boredSage** [comment] 2024-07-23 19:48
This feature should at least be made available for ANIME since there's no workaround for it. For manga, you can you use forks with the feature, like SY or J2K, and then go back to Aniyomi, which is still annoying but it's a solution.

It is also time-consuming, especially for those with over 1.5k manga in their library (yeah that's me) since creating a backup, restoring it to SY and restoring it back to Aniyomi takes a while. Last time I did it, if I remember correctly the first restoration took 30 minutes and the second 40 minutes.

**Comment by Secozzi** [comment] 2024-08-14 00:05
Duplicate of #777

**Closed by Secozzi** 2024-08-14 00:05 UTC
