### ISSUE TITLE
Can't download or update manga or anime extensions...

### ISSUE THREAD

**Issue by joshuaj03** [aniyomiorg/aniyomi#396] opened 2022-02-13 06:00 UTC
### Steps to reproduce

1. Open manga/anime extension tab 
2. Just download any of the desired ones

### Expected behavior

I wanted to download them and be usable.

### Actual behavior

No extensions where downloaded even after trying various other extensions. I can't even update the existing anime extensions.

It shows downloading/updating ,but after a couple of minutes, it revert back to update/download.

### Crash logs

There wasn't any crash log, those manga extension just didn't download.

### Aniyomi version

aniyomi-arm64-v8a-v0.12.3.6

### Android version

Android 8.0

### Device

Asus Zenfone Max M1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment] 2023-07-06 17:07
Duplicate of #843

**Closed by Quickdesh** 2023-07-06 17:07 UTC
