### ISSUE TITLE
Screen mirroring/chromecast

### ISSUE THREAD

**Issue by Omab12** [aniyomiorg/aniyomi#630] opened 2022-06-28 21:01 UTC
### Describe your suggested feature

maybe put screen mirroring or chrome casting on anime/player so it's accessible to play on TV or other devices.

### Other details

An idea not an issue.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [x] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [x] I have updated the app to version **[0.12.3.6](https://github.com/jmir1/aniyomi/releases/latest)**.
- [x] I will fill out all of the requested information in this form.

**Comment by jackie5602** [comment] 2022-08-05 04:56
I like this idea, but you can also do this by playing externally and casting it

**Comment by 12ohit** [comment] 2022-08-05 05:00
Duplicate of #78 and/or #360

**Closed** 2024-01-14 20:44 UTC
