### ISSUE TITLE
Can't play any video and not able to get the extension list

### ISSUE THREAD

**Issue by YourBetterOne** [aniyomiorg/aniyomi#415] opened 2022-02-24 11:45 UTC
### Steps to reproduce

After some buffering it shows expected url error and always failed to get extensions list

### Expected behavior

I expect it to open in first try

### Actual behavior

But it's always buffering 

### Aniyomi version

0.12.3.6

### Android version

Android 10

### Device

RMX1851

### Other details

![Screenshot_20220224-170804_Aniyomi](https://user-images.githubusercontent.com/100353848/155517872-666caa0f-0a11-4afc-989e-ab37c1c81f31.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jsom25** [comment] 2022-02-27 11:26
I am also getting the same error with these extensions too

**Comment by Quickdesh** [comment] 2023-07-06 17:07
Duplicate of #843

**Closed by Quickdesh** 2023-07-06 17:07 UTC
Labels: duplicate
