### ISSUE TITLE
Add support for Amazon Firestick

### ISSUE THREAD

**Issue by Nexus-Gits** [aniyomiorg/aniyomi#1347] opened 2024-01-23 13:12 UTC
### Describe your suggested feature

Add support for Amazon Firestick. App install but navigation not good and settings page not work. Please fix this issue with firefox

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by EfeDevirgen** [comment] 2024-02-01 16:33
The devs are not thinking about making a TV UI but you can always do it yourself :)

**Comment by LittleFreak** [comment] 2024-02-10 00:26
Amazon has confirmed, that they move away from all Fire* devices from Android and even migrate old ones with an coming update.
<details><summary>Sources</summary>
<p>
https://www.golem.de/news/amazon-neuartiges-fire-tv-geraet-ohne-fire-os-in-planung-2401-181723.html
https://t3n.de/news/amazon-fire-android-abschied-vega-os-1605178/
</p>
</details> 
So there wouldn't be a point to invest time for compatibility at this point.

**Comment by mobby45** [comment] 2024-02-28 01:31
I've found the best solution for this, with the downloader app, enter in url 28907 goes into tool and search for mouth toggle and install it, if you don't find do internet search

**Comment by abdallahmehiz** [comment] 2024-08-11 11:19
Duplicate of #162

**Closed by abdallahmehiz** 2024-08-11 11:19 UTC
