### ISSUE TITLE
Add option to edit an entry's info (tags, cover, title, author, etc.)

### ISSUE THREAD

**Issue by BraveSoldat** [aniyomiorg/aniyomi#1509] opened 2024-03-20 06:26 UTC
### Describe your suggested feature

It would be great if Aniyomi added an option on the 3dot menu to edit the current entry's info.
The info would range from the cover and the title of the entry, to the author and the tags, to anything else.

This has been implemented on TachiyomiSY and works great.

![Screenshot_20240320_032155_TachiyomiSY](https://github.com/aniyomiorg/aniyomi/assets/156040435/ed8e6e90-4086-450f-b3d8-7db462cc29f4)

### Other details

This would be particularly useful for local entries. Tag editing is a must have.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [x] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment] 2024-08-11 11:09
Duplicate of #1313

**Closed by abdallahmehiz** 2024-08-11 11:09 UTC
