### ISSUE TITLE
"Edit info" Feature 

### ISSUE THREAD

**Issue by ghost** [aniyomiorg/aniyomi#1313] opened 2024-01-17 15:16 UTC
### Describe your suggested feature

Just like TachiyomiSY, the feature to edit the information of the anime and manga we add to the library.
![IMG_20240117_170716](https://github.com/aniyomiorg/aniyomi/assets/146931879/451cf1f6-2c63-4a90-b953-e9cae17ae20e)
![IMG_20240117_170616](https://github.com/aniyomiorg/aniyomi/assets/146931879/a0c0ae46-005e-461b-9359-c86c098ab9ef)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.2](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by LittleFreak** [comment] 2024-02-10 00:44
Duplicate of #237 and #1384

**Comment by Secozzi** [comment] 2024-08-22 20:59
Duplicate of #237

**Closed by Secozzi** 2024-08-22 20:59 UTC
