### ISSUE TITLE
Add Schedule Airing Feature.

### ISSUE THREAD

**Issue by Swetank45** [aniyomiorg/aniyomi#1789] opened 2024-09-22 07:51 UTC
### Describe your suggested feature

Hello! Please add this (Schedule Airing) feature. 
This feature helps you to find ongoing,upcoming animes for a week. 
This feature has been used by many anime sites like miruro etc. but they don't have anime app.
So I hope you add this feature.
Thank you.

### Other details

![Schedule Airing Feature On Miruro](https://github.com/user-attachments/assets/6229850e-f0e9-490a-95f5-5e94735ada15)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is a request regarding an extension, I should be opening an issue in the extension's repository.
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-09-22 07:52
Duplicate of #1414

**Closed by Secozzi** 2024-09-22 07:52 UTC
Labels: Feature request
