### ISSUE TITLE
Mal tracker not work

### ISSUE THREAD

**Issue by Domipoke** [aniyomiorg/aniyomi#1475] opened 2024-03-03 14:27 UTC
### Steps to reproduce

Is not possible to connect Myanimelist.net tacker.
I click on Mal tracker, I login and allow it but when I get redirect to aniyomi nothing change. I'm still not logged in.

### Expected behavior

tracker connected

### Actual behavior

Tracker is not connected

### Aniyomi version

0.15.2.4

### Android version

Android 13

### Device

Xiaomi 220116TG (viva)

### Other details

This issue can't be redirected to Tachiyomi because Tachiyomi will not more support the project.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by LittleFreak** [comment] 2024-03-08 09:58
Duplicate of #1397

**Comment by Secozzi** [comment] 2024-08-15 16:59
This has most likely been fixed in the [preview](https://github.com/aniyomiorg/aniyomi-preview/releases/) version with the merge from Mihon. If the issue still persists even after switching to preview or in the next stable update, please open a new issue.

**Closed by Secozzi** 2024-08-15 16:59 UTC
