### ISSUE TITLE
Multiple device usage

### ISSUE THREAD

**Issue by sBaydin** [aniyomiorg/aniyomi#1510] opened 2024-03-22 01:10 UTC
### Describe your suggested feature

It would be great to have the app synchronized across multiple devices (phone, tablet, TV, etc.). The fact that the lists are different on each device makes it difficult to track watched and not watched. I think such a feature would be good.
Thank you.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by shinobs** [comment] 2024-04-10 01:33
That'd be nice indeed.

**Comment by Lolen10** [comment] 2024-04-12 12:16
duplicate of #1330

**Comment by sBaydin** [comment] 2024-04-13 20:52
> duplicate of #1330

[i think thats not the ](https://github.com/aniyomiorg/aniyomi/issues/1330#issuecomment-1912910431) my opinion is the same with that answer.

**Comment by Lolen10** [comment] 2024-04-13 20:55
> [my opinion is the same with this answer. ](https://github.com/aniyomiorg/aniyomi/issues/1330#issuecomment-1912910431)

[TachiyomiSY](https://github.com/jobobby04/TachiyomiSY) already implemented it. There you have the choice between Google Drive and selfhosted (Syncyomi). I think if it will be implemented it will be similar to the implementation of TachiyomiSY.

**Comment by sBaydin** [comment] 2024-04-13 20:59
> > [my opinion is the same with this answer. ](https://github.com/aniyomiorg/aniyomi/issues/1330#issuecomment-1912910431)
> 
> [TachiyomiSY](https://github.com/jobobby04/TachiyomiSY) already implemented it. There you have the choice between Google Drive and selfhosted (Syncyomi). I think if it will be implemented it will be similar to the implementation of TachiyomiSY.

It makes sense. If a similar option is made, aniyomi will skyrocket :)

**Closed** 2024-08-14 12:25 UTC
