### ISSUE TITLE
Can't watch anime "this file cannot be play"

### ISSUE THREAD

**Issue by Mysusygatto001** [aniyomiorg/aniyomi#1549] opened 2024-04-22 18:07 UTC
### Steps to reproduce

Hi I'm having issue, I newly tried aniyomi. But after I download some episode I can't watch it and set the player to external, the video cannot be play and says "file cannot be play" . So I try setting the payer to the default player and redownload some episodes. And the result is still the same

### Expected behavior

I expected that the second step should make it

### Actual behavior

Cannot play video

### Crash logs

[aniyomi_crash_logs.txt](https://github.com/aniyomiorg/aniyomi/files/15067077/aniyomi_crash_logs.txt)

### Aniyomi version

0.15.2.4

### Android version

Android 11

### Device

Infinix HOT 11 play 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Mysusygatto001** [comment] 2024-04-23 12:57
Please someone send help :)

**Comment by fakebhai** [comment] 2024-04-23 13:23
> Please someone send help :)

you can try using external Downloader if you're having issues, join Aniyomi's [discord](https://discord.gg/F32UjdJZrR) for external Downloader guide.
adm, 1dm,1dm+ are supported.

**Comment by Secozzi** [comment] 2024-08-14 10:54
Duplicate of #1326

**Closed by Secozzi** 2024-08-14 10:54 UTC
