### ISSUE TITLE
Group multiple seasons of the same show 

### ISSUE THREAD

**Issue by ShoaibKhanali** [aniyomiorg/aniyomi#1832] opened 2024-11-20 13:09 UTC
### Describe your suggested feature

It would be nice if we could group multiple related entries into a single entry. The episode/chapter list would have tabs similar to the categories in the library view, or have them all as one big list. Potentially both but customizable.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is a request regarding an extension, I should be opening an issue in the extension's repository.
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-11-27 15:08
Duplicate of #127

**Closed by Secozzi** 2024-11-27 15:08 UTC
Labels: Feature request
