### ISSUE TITLE
Making navigation easy on android tv

### ISSUE THREAD

**Issue by Naonga** [aniyomiorg/aniyomi#1376] opened 2024-01-30 09:27 UTC
### Describe your suggested feature

If by any chance you could make navigation easy to use with a remote and if possible you also add in an android tv icon, it doesn't show in Chromecast with Google tv. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by elvistony** [comment] 2024-02-11 12:35
I would like to help out, I'm not an expert in android development (just barely made a tiny app few years ago) but if anyone would like to work on it together feel free to drop by.

Seeing this has been raised multiple times here (#114, #162, #229, #854, #751, #1347 ,#1006), we could make this work. If we make it stable enough, we could have a pull request made and @jmir1 could review and merge it in no time!

I believe the task should be relatively straightforward:
- Set Focus Handling properties for the UI Elements [Android Docs](https://developer.android.com/reference/android/view/View#FocusHandling) This should help the remotes move around the selection without integrating a mouse.
- Add an appearance theme to the library to show selected items in a more brighter colour

**Comment by elvistony** [comment] 2024-02-12 22:49
I've started to work on the app on my [fork](https://github.com/elvistony/aniyomi-tv-beta), I've tried adding **NextFocus** Properties (firstly) to the `player_controls.xml` but the DPAD interactions doesn't navigate correctly even after disabling the **KeyDown** events in the Gestures function. 

Anybody knows what's going wrong?

Idea references:
- [Focus Events - Android Docs](https://developer.android.com/reference/android/view/View#FocusHandling)
- [Making apps TV friendly - Amazon Dev](https://developer.amazon.com/apps-and-games/blogs/2021/06/tutorial-add-touch-interactions-to-android-based-apps-on-fire-tv)

**Comment by Dark25** [comment] 2024-02-15 16:25
What happens is that aniyomi is divided by modules, you must specify where it should jump when it reaches (x) or (y)

**Comment by elvistony** [comment] 2024-02-15 22:11
True! But since it's not a mouse pointer based solution, it just tells where the next selection box needs to go when the DPAD arrow keys are pressed.

I tried this out, and some stuff seem to work, but I need an expert 😂 to help me out. I'm editing the xml file of the layout and adding the `NextFocusRight` ...  to the attributes, but for some reason the focus finding algorithm ignores these properties.

**Comment by Dark25** [comment] 2024-02-15 22:24
> True! But since it's not a mouse pointer based solution, it just tells where the next selection box needs to go when the DPAD arrow keys are pressed.
> 
> I tried this out, and some stuff seem to work, but I need an expert 😂 to help me out. I'm editing the xml file of the layout and adding the `NextFocusRight` ... to the attributes, but for some reason the focus finding algorithm ignores these properties.

I recommend you join the official aniyomi server, so you can talk more comfortably with more developers

https://discord.gg/Emm7xgSh

**Comment by sBaydin** [comment] 2024-03-10 15:20
Hello, I don't know if this is the right place, but I would like to raise a small issue.
Yes, control with the remote control is a bit of a problem. Mouse control is better. But there is a problem in scrolling down by dragging the lists while controlling with the mouse. I would like to make a notification about this issue. Maybe this is not the place for this, I apologize in advance.

**Comment by deenodadon** [comment] 2024-03-10 16:08
aniyomi works on android tv kinda with the cloudstream extension but i don't think its actively maintained a lot of aniyomi extensions don't work on it rn but i believe its because webview is not implemented in this extension but im no expert maybe this could help  https://github.com/CranberrySoup/AniyomiCompatExtension

**Comment by abdallahmehiz** [comment] 2024-08-11 11:19
Duplicate of #162

**Closed by abdallahmehiz** 2024-08-11 11:19 UTC
