### ISSUE TITLE
Synchronise anime tracking page tags (MAL, Anilist, etc...) with Aniyomi

### ISSUE THREAD

**Issue by AntonioJoseMunozEscobar** [aniyomiorg/aniyomi#1479] opened 2024-03-04 13:24 UTC
### Describe your suggested feature

It would be a good idea to be able to sync according to the tags you have on the page itself to the anime or manga categories of Aniyomi.

For example:

MyAnimeList has the following tags:

- Watching
- Completed
- On Holding
- Dropped
- Plan To Watch

I would add an option to import the MAL data into Aniyomi (I don't know if you can add an extra step to choose which extensions you want to use to search for those anime) and have all your MAL anime record in Aniyomi.

### Other details

It might be interesting to later introduce a volumetrics section within the app so that you can see more detailed data about which anime you are watching.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-08-14 11:09
Duplicate of #381

**Closed by Secozzi** 2024-08-14 11:09 UTC
