### ISSUE TITLE
Manga extensions stopped working

### ISSUE THREAD

**Issue by jyash8** [aniyomiorg/aniyomi#926] opened 2023-03-02 12:58 UTC
### Steps to reproduce

1. Go to Browse
2. Then go to manga extensions

### Expected behavior

Manga extensions are not shown in manga extensions section

### Actual behavior

Manga extensions shown properly and can be downloaded

### Aniyomi version

0.12.3.10

### Android version

Android 7

### Device

Redmi note 4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by luddystefenson** [comment] 2023-03-22 21:16
"Failed to get extensions list" is what I'm getting while trying to add manga extensions. Works fine on Tachiyomi, only an issue with Aniyomi. I have tried 0.12.3.9, 0.12.3.8, and 0.12.3.6. Anime extensions work fine though!

**Comment by AnujChandel** [comment] 2023-04-01 06:53
This shows for me

![Screenshot_2023-04-01-12-21-07-15_dd604340c1d7941d42aee14dd16e00e8](https://user-images.githubusercontent.com/103368827/229270656-bff40cd2-1f60-4f55-b435-809e7034e724.jpg)

**Comment by Quickdesh** [comment] 2023-06-16 12:09
Duplicate of #844

**Closed by Quickdesh** 2023-06-16 12:09 UTC
