### ISSUE TITLE
Crash on rotating screen twice

### ISSUE THREAD

**Issue by suhaien** [aniyomiorg/aniyomi#1493] opened 2024-03-12 00:44 UTC
### Steps to reproduce

1. Open aniyomi
2. Rotate screen twice
3. Crash.

### Expected behavior

The app should not crash.

### Actual behavior

The app crashes.

### Aniyomi version

r7513

### Android version

LineageOS 20 (Android 13)

### Device

Samsung S9

### Other details

https://github.com/aniyomiorg/aniyomi/assets/129636286/016bfabd-8617-4d1c-b1d0-50bd8f66536d

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by shubham926** [comment] 2024-03-22 16:26
I have the same issue. App also crashes when I press back while in video player. Its also connected to rotation issue.

**Comment by suhaien** [comment] 2024-03-22 16:55
App still crashes on my device even with auto rotate turned off.

https://github.com/aniyomiorg/aniyomi/assets/129636286/1e8bf091-2956-4757-98c7-9243726256fa

**Comment by abdallahmehiz** [comment] 2024-08-11 11:08
I am guessing this was because of a bug caused by the main activity creating an mpv instance twice. This was fixed on 71e0d44a0b82a708342a8b22e108dd051e2c1615

**Closed by abdallahmehiz** 2024-08-11 11:08 UTC
