### ISSUE TITLE
Failed to get extensions list

### ISSUE THREAD

**Issue by ghost** [aniyomiorg/aniyomi#900] opened 2023-02-18 00:47 UTC
### Steps to reproduce

Every time i try to install a new manga extension
I won't load the list

### Expected behavior

The screen still empty and give me ( failed to get extensions list)

### Actual behavior

It should show me the extension but it doesn't show up 

### Aniyomi version

0.12.3.10

### Android version

12

### Device

Samsung galaxy m52

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Samscryption** [comment] 2023-02-18 05:19
I have the same problem,
It started accruing after I updated all manga extensions in tachiyomi j2k.
They seem to show up fine in j2k but it refuses to in aniyomi.

**Comment by Ankurrawat-12** [comment] 2023-02-18 20:18
Same issue after i updated extensions by tachiyomi

**Comment by Applewubs** [comment] 2023-02-18 20:31
Same issue, but if you clean install the app all the new updated extensions disappear

**Comment by Ankurrawat-12** [comment] 2023-02-18 20:51
yup

**Comment by candyjam4u** [comment] 2023-02-19 02:28
![Screenshot_20230219_032727_Aniyomi](https://user-images.githubusercontent.com/80989495/219908858-6c591ea4-1b68-49be-bcba-00fbe238711a.jpg)
![Screenshot_20230219_032653_Aniyomi](https://user-images.githubusercontent.com/80989495/219908860-e8af3769-b916-47f9-89ee-452453b629f5.jpg)

**Comment by lakshya2543** [comment] 2023-02-19 06:32
Same problem

**Comment by Ankurrawat-12** [comment] 2023-02-19 18:35
Any updates

**Comment by SANCTI-afk** [comment] 2023-02-21 02:59
Same issue after Updating extensions in tachiyomi

**Comment by JhDeLy-WB** [comment] 2023-02-21 11:31
Que hago para resolver el problema???

**Comment by MikaelaMuller** [comment] 2023-02-23 14:31
![Screenshot_20230223-222500_Aniyomi](https://user-images.githubusercontent.com/91151184/220936499-0cb219f7-8b99-48d5-9e61-d9eda556f680.jpg)
Updating my extensions using another tachiyomi client made all of them disappear.

**Comment by Applewubs** [comment] 2023-02-23 20:06
For now you can use other Tachiyomi fork untill this one gets updated, is not the end of the world

**Comment by Samscryption** [comment] 2023-02-23 21:07
I installed aniyomi beta and it works alright 
The performance is kinda terrible and there's frequent crashes since it's an experimental version but the extentions work fine at least

**Comment by Timi-19** [comment] 2023-04-02 16:28
I am also experiencing this issue on my Tachiyomi SY too. I wanted to install a new extension and it told me failed to get extensions list. What do I do?

**Comment by shefski55555** [comment] 2023-05-03 10:01
Probably won't be the fix for all but I got this error when trying to update via data connection (which I'd forgotten I'd restricted Tachiyomi's access to). So basically I'm saying if you've googled this issue do a once over of your network connection because it could be that. Maybe worth looking at potentially giving a more specific error message for this case? Although I admit my situation was a pretty niche scenario.

**Comment by Habibalariqi** [comment] 2023-05-19 15:39
نرجو حل المشكله

**Comment by Quickdesh** [comment] 2023-06-16 12:08
Duplicate of #844

**Closed by Quickdesh** 2023-06-16 12:08 UTC

**Comment by Dt7768181** [comment] 2024-01-09 16:19
i got the solution
add this repo to get all the extensions
https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json

**Comment by Secozzi** [comment] 2024-01-09 16:26
@Dt7768181 Do not share third party extensions on github
