### ISSUE TITLE
Add tracking for two different anime in a single entry

### ISSUE THREAD

**Issue by lalalasupa0** [aniyomiorg/aniyomi#1500] opened 2024-03-15 19:15 UTC
### Describe your suggested feature

To be able to add another anime to a single tracking service since in AniList (for example) entries that in aniyomi sources are as "...ovas" in AniList they are separately.

Example:
On aniyomi source: "Bleach: OvaS"
On AniList: "Ova 1" & "Ova 2"

### Other details

It would be useful to not have to add more entries to the library, and if someone keeps an order (by date added to the library) so that it doesn't get cluttered when adding new entries just to add tracking to each episode that are like different entries in AniList.

Although, a solution for this would be to create a category just to add tracking to those "episodes" that are as different entries in AniList.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Lolen10** [comment] 2024-03-17 17:18
+1

This would be useful for entries with multiple seasons too.

**Comment by edmxn** [comment] 2024-03-17 17:59
> +1
> 
> This would be useful for entries with multiple seasons too.

Exactly, like Yomiroll, in fact

**Comment by Secozzi** [comment] 2024-08-15 16:18
Duplicate of #1351

**Closed by Secozzi** 2024-08-15 16:18 UTC
