### ISSUE TITLE
Merge manga from multiple sources

### ISSUE THREAD

**Issue by priyanshu-singhania** [aniyomiorg/aniyomi#1595] opened 2024-06-02 02:25 UTC
### Describe your suggested feature

Merge anime/manga from multiple sources with same title and dedupe it in order of priority just like in TachiyomiSY.

### Other details

This feature is available in TachiyomiSY.
https://github.com/jobobby04/tachiyomisy

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.3.0](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-08-14 00:04
Duplicate of #127

**Closed by Secozzi** 2024-08-14 00:04 UTC
