### ISSUE TITLE
Best usefull Feature 🤝

### ISSUE THREAD

**Issue by Unknown07070** [aniyomiorg/aniyomi#1371] opened 2024-01-28 17:17 UTC
### Describe your suggested feature

![Screenshot_2024-01-28-16-35-48-30_5a5d49abde8a8d0016709e110e7f41e4](https://github.com/aniyomiorg/aniyomi/assets/131685490/5d436c3e-73b9-4100-87bb-fd2e287fc517)

![Screenshot_2024-01-28-16-32-04-58_423fe07c33ed17f15a4e92e5e3a15972](https://github.com/aniyomiorg/aniyomi/assets/131685490/321ad908-3cad-4b50-8a4f-8f13c52a2c7a)

I want to migrate local source with extensions.
So simply make a option so we can ( Migrate past anime library's into local library )

### Other details

I want to or from my migrate local source.
So simply make a option so we can ( Migrate past anime library's into local library )

🤝🤝🤝 please It's  really really extremely usefull feature. So we can sync Between local source and saved sources from extensions

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment] 2024-08-11 11:35
Duplicate of #1370

**Closed by abdallahmehiz** 2024-08-11 11:35 UTC
