### ISSUE TITLE
Add Grouping in shorting

### ISSUE THREAD

**Issue by suraj3486** [aniyomiorg/aniyomi#172] opened 2021-09-22 07:41 UTC
### Describe your suggested feature

In Grouping manga or anime should be grouped according to CATEGORIES, SOURCES, STATUS, UNGROUPED etc. By grouping manga or anime it will be quite helpful.
Other forks of tachiyomi have this setting.
![Screenshot_20210922-130039627](https://user-images.githubusercontent.com/54233248/134302581-06ea8fe9-d930-4824-80b4-ed2939ad8dbb.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.2.3](https://github.com/jmir1/aniyomi/releases)**.
- [X] I will fill out all of the requested information in this form.

**Comment by 12ohit** [comment] 2022-07-08 06:04
Duplicate of #87

**Closed** 2023-07-06 17:01 UTC
Labels: duplicate
