### ISSUE TITLE
Separate backup for anime and manga

### ISSUE THREAD

**Issue by Character95** [aniyomiorg/aniyomi#1575] opened 2024-05-12 19:51 UTC
### Describe your suggested feature

add Separate backup for anime and manga 

I use stable and preview version of the app and it's easier if can separate anime and manga in backup or to choose only one of them to sync with other apps

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.3.0](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Character95** [comment] 2024-05-31 08:13
And to sync with other apps

**Comment by Secozzi** [comment] 2024-08-14 10:32
Duplicate of #1127

**Closed by Secozzi** 2024-08-14 10:32 UTC
