### ISSUE TITLE
Download probkems

### ISSUE THREAD

**Issue by PHBN1964** [aniyomiorg/aniyomi#1359] opened 2024-01-27 02:01 UTC
### Steps to reproduce

1.Choose an anime
2.Download the Episode

### Expected behavior

The episode should be downloaded

### Actual behavior

The episode is marked as downloaded but when I tried to watch it says that video list is empty and there is a notification on my cellphone saying that the series episode was "standalone couroutine was cancelled", this is happening in multiple extensions

### Aniyomi version

00.15.2.3

### Android version

Android 12 S

### Device

Moto G30

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by LittleFreak** [comment] 2024-01-29 18:38
Duplicate of #1326

**Closed** 2024-08-11 11:34 UTC
