### ISSUE TITLE
Manga extension

### ISSUE THREAD

**Issue by sleepysloth18** [aniyomiorg/aniyomi#1010] opened 2023-05-29 10:57 UTC
### Steps to reproduce

Open the app, go to browse and open manga extension 's

### Expected behavior

Installed and unustalled sources

### Actual behavior

Only installed sources and the sources some are not responding 

### Aniyomi version

0.12.3.10

### Android version

9

### Device

Redmi note 5 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2023-05-30 20:06
Fix manga extensions not loading by downloading preview from [the website](https://aniyomi.org/download/)

**Comment by Quickdesh** [comment] 2023-06-16 12:05
Duplicate of #844

**Closed by Quickdesh** 2023-06-16 12:05 UTC
