### ISSUE TITLE
Option to Edit episode number for extensions that provide multiple season under one title 

### ISSUE THREAD

**Issue by Luffyirl** [aniyomiorg/aniyomi#1490] opened 2024-03-09 11:34 UTC
### Describe your suggested feature

A option to edit episode numbers for sources that have multiple season under one name and tend to have bad namings (such as - not  season 2 numbering from 13 or 24 insted of 1) .while tracking with season one for example works fine , tracking after that season starts from 12 or 24 and sometimes gets marked completed . A option to edit episode number would help us to renumber the episodes to track them properly.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-08-15 16:29
Duplicate of #42

**Closed by Secozzi** 2024-08-15 16:29 UTC
