### ISSUE TITLE
Anime won't track while using external player

### ISSUE THREAD

**Issue by SacredGenius07** [aniyomiorg/aniyomi#1676] opened 2024-07-10 08:24 UTC
### Steps to reproduce

1. Watch any anime episode in external player 
2. Open tracking option 

### Expected behavior

It should track if I watch the anime episode in external player.

### Actual behavior

The anime episode I watched on external player doesn't get tracked.

### Aniyomi version

0.16.4.3

### Android version

11

### Device

Poco M2

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official anime extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with a manga extension, report it to the manga source extension project you added it from.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.3.0](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-08-15 16:31
Duplicate of #1331

**Closed by Secozzi** 2024-08-15 16:31 UTC
Labels: Bug
