### ISSUE TITLE
Google tv support

### ISSUE THREAD

**Issue by MarlonPMan** [aniyomiorg/aniyomi#1712] opened 2024-07-19 06:51 UTC
### Describe your suggested feature

so I tried side-loading the app on my Google TV stick it works ok the problem is navigation and the video playback is very bad

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is a request regarding an extension, I should be opening an issue in the extension's repository.
- [x] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment] 2024-08-11 10:46
Duplicate of #162

**Closed by abdallahmehiz** 2024-08-11 10:46 UTC
