### ISSUE TITLE
Device tap zones are not aligned correctly

### ISSUE THREAD

**Issue by ShoyebOP** [aniyomiorg/aniyomi#1294] opened 2024-01-15 12:13 UTC
### Steps to reproduce

1.open aniyomi app.
2. Open any manga
3. Select any tap zones style (example: edge)

### Expected behavior

Selecting the edge or whatever tap zone style a preview is shown and if we tap on the corresponding place the designated action should happen(example: for edge style tapping on anywhere of your left and right edges should make your manga go a page forward)

### Actual behavior

But instead if you tap on corresponding places it doesn't work property it's completely random where you tap and what will happen 

### Aniyomi version

App version: 0.15.2.1-7454 (standard, 61c70597a, 119, 2024-01-14T23:36Z)

### Android version

Android version: 13 (SDK 33; build lineage_cheeseburger-userdebug 13 TQ3A.230901.001 c666ad56da) Android build ID: lineage_cheeseburger-userdebug 13 TQ3A.230901.001 c666ad56da

### Device

Device brand: OnePlus Device manufacturer: OnePlus Device name: OnePlus5 (OnePlus5) Device model: ONEPLUS A5000

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.1](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment] 2024-01-15 12:18
Can you record video of something like this happening cause i am not able to reproduce

**Comment by abdallahmehiz** [comment] 2024-01-15 12:18
Can you record video of something like this happening cause i am not able to reproduce

**Comment by ShoyebOP** [comment] 2024-01-15 12:30
> Can you record video of something like this happening cause i am not able to reproduce


> Can you record video of something like this happening cause i am not able to reproduce


https://github.com/aniyomiorg/aniyomi/assets/115879044/1a3f547f-6329-45b9-baae-2795d7ec4cbc

**Comment by abdallahmehiz** [comment] 2024-01-15 12:42
It's happening only with long strips

**Comment by jmir1** [comment] 2024-01-20 12:47
Could be resolved by https://github.com/aniyomiorg/aniyomi/commit/c65a9aecf5ed228550fd994e62a16fc2300c344d

**Comment by ShoyebOP** [comment] 2024-01-23 17:27
> Could be resolved by [c65a9ae](https://github.com/aniyomiorg/aniyomi/commit/c65a9aecf5ed228550fd994e62a16fc2300c344d)

How can I do that?

I thought it would be implemented in the new update but it's still not fixed.

**Comment by jmir1** [comment] 2024-01-23 18:22
You don't have to do anything
The fix will be in the 0.15.3.0 release.

**Comment by hollowshiroyuki** [comment] 2024-02-17 14:34
The fix is coming from upstream, it'll be added on next merge i.e. in the 0.15.3.0 version
https://github.com/aniyomiorg/aniyomi/pull/1377

**Comment by jmir1** [comment] 2024-05-10 08:30
fixed by 5f5915b25cc588561fdf34a416ed2c2538c387a0

**Closed by jmir1** 2024-05-10 08:30 UTC
Labels: bug
