### ISSUE TITLE
Manga extensions issue 

### ISSUE THREAD

**Issue by Nebulavargas** [aniyomiorg/aniyomi#1166] opened 2023-10-20 17:25 UTC
### Steps to reproduce

1.  Open manga extensions 

### Expected behavior

2. The manga extensions list appears

### Actual behavior

3.  "Failed to get extensions list" and extensions list is empty

### Aniyomi version

0.12.3.10

### Android version

Android 10

### Device

Xiaomi Redmi note 7

### Other details

When I download the Aniyomi preview version, the manga extensions show up. But when I download the stable version, it says "Failed to get extensions list". 

1. Aniyomi v0.12.3.10 Stable version
![IMG_20231020_200549](https://github.com/aniyomiorg/aniyomi/assets/146843923/a57652de-7146-45e0-96a8-697bbbf7d48d)

2. Aniyomi Preview r6670 version
![IMG_20231020_201233](https://github.com/aniyomiorg/aniyomi/assets/146843923/caad448b-18b0-42d5-977b-cd7e1ab7dc3b)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/help/faq/) and [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment] 2023-10-20 18:20
duplicate of #844

**Closed by abdallahmehiz** 2023-10-20 18:20 UTC
