### ISSUE TITLE
Hold to change playback speed

### ISSUE THREAD

**Issue by syzo00** [aniyomiorg/aniyomi#1662] opened 2024-07-04 04:03 UTC
### Describe your suggested feature

um I'm thinking about a feature that if you hold the screen while watching the anime the playback speed will change to 2x

### Other details

this feature is available on the app Called loklok and bilibili if you know that

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.3.0](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by SacredGenius07** [comment] 2024-07-10 08:16
I really want this feature too. It's just so much helpful and I totally don't need to seek if I have this.

**Comment by boredSage** [comment] 2024-07-23 19:29
Feature also available in youtube

**Comment by abdallahmehiz** [comment] 2024-08-11 10:43
How would this work with the current share sheet?

**Comment by abdallahmehiz** [comment] 2024-08-11 10:51
also i just noticed, you opened the same feature request twice. Please refrain from doing so.
Duplicate of #1660

**Closed by abdallahmehiz** 2024-08-11 10:51 UTC
