### ISSUE TITLE
Issue: Aniyomi Randomly(sometimes consistently) freezes while watching anime.

### ISSUE THREAD

**Issue by MikaelaMuller** [aniyomiorg/aniyomi#1399] opened 2024-02-05 07:24 UTC
### Steps to reproduce

Simply Watch Pacific Rim Black on Gogoanime 
Watch Pacific Rim on Sflix(inconsistent) 

### Expected behavior

It should play without issue

### Actual behavior

After a few seconds the application simply freezes.
The issue seems random at first but it seems to happen consistently on 60fps videos. 
![Screenshot_20240205-151155_Aniyomi](https://github.com/aniyomiorg/aniyomi/assets/91151184/9895cbae-7c3c-4755-9a4e-da9e76748720)

### Crash logs

[aniyomi_crash_logs (2).txt](https://github.com/aniyomiorg/aniyomi/files/14161724/aniyomi_crash_logs.2.txt)
[aniyomi_crash_logs (3).txt](https://github.com/aniyomiorg/aniyomi/files/14161725/aniyomi_crash_logs.3.txt)
[aniyomi_crash_logs (1).txt](https://github.com/aniyomiorg/aniyomi/files/14161728/aniyomi_crash_logs.1.txt)

I have verbose logging turned on each log.

### Aniyomi version

App version: 0.15.2.4-7493 (standard, 89795945a, 121, 2024-01-31T13:51Z) Android version: 12 (SDK 32; build SQ3A.220705.004) Android build ID: SQ3A.220705.004 Device brand: samsung Device manufacturer: samsung Device name: a02q (a02qnaxx) Device model: Samsung Galaxy A02S WebView: Android System WebView 122.0.6261.15

### Android version

Android 12

### Device

Samsung Galaxy A02s

### Other details

Device is rooted and Running on a GSI. 
In addition i managed to capture one of these freezes on logcat
This issue seems to also occur when a priority notification pops up

Logcat:
[logcat_02-05-2024_15-13-51.txt](https://github.com/aniyomiorg/aniyomi/files/14161752/logcat_02-05-2024_15-13-51.txt)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MikaelaMuller** [comment] 2024-02-06 19:21
... please don't go stale

**Comment by Secozzi** [comment] 2024-08-22 20:12
Duplicate of #1249

**Closed by Secozzi** 2024-08-22 20:12 UTC
