### ISSUE TITLE
Complicated scrolling in the download queue

### ISSUE THREAD

**Issue by Liametekudasai** [aniyomiorg/aniyomi#1469] opened 2024-02-27 18:03 UTC
### Steps to reproduce

Scroll up or down in the download queue either in anime or manga

### Expected behavior

Should scroll up or down without needing extreme precision

### Actual behavior

When scrolled up or down to see the queued entries it often scrolls left or right to go to anime or manga download page even while being quite precise

### Aniyomi version

0.15.2.4

### Android version

Android 14

### Device

Samsung galaxy A34 5G ; SM-A346B/DSN

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-08-15 17:10
Duplicate of #1215

**Closed by Secozzi** 2024-08-15 17:10 UTC
