### ISSUE TITLE
Migration request 

### ISSUE THREAD

**Issue by MonomoySama** [aniyomiorg/aniyomi#1740] opened 2024-08-05 07:50 UTC
### Describe your suggested feature

Single migration takes toooo much time and is a hassle when you have a lotttt of content in  library, so i wanted a mass migration option

### Other details

I'm sure it's not only my problem...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is a request regarding an extension, I should be opening an issue in the extension's repository.
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment] 2024-08-05 07:58
Duplicate of #777

**Closed by abdallahmehiz** 2024-08-05 07:58 UTC

**Comment by MonomoySama** [comment] 2024-08-05 07:59
> Duplicate of #777

A duplicate from 2022... But still the feature is not here... So is it not possible or something?

**Comment by abdallahmehiz** [comment] 2024-08-05 08:03
It is very much possible, if a developer wanted to add i am pretty sure the pr would accepted, but no one has done that yet

**Comment by MonomoySama** [comment] 2024-08-05 08:06
> It is very much possible, if a developer wanted to add i am pretty sure the pr would accepted, but no one has done that yet

It's a much wanted feature tho for an app like this
