### ISSUE TITLE
Aniyomi force stops when you exit from anime

### ISSUE THREAD

**Issue by KeremDgGG** [aniyomiorg/aniyomi#1484] opened 2024-03-06 12:17 UTC
### Steps to reproduce

1. Open an anime episode
2. When the video started to play, leave from the video either with Aniyomi back button or phone's back button
3. Aniyomi force stops

### Expected behavior

Showing anime library

### Actual behavior

Force stops and drops you to phone main screen

### Aniyomi version

0.15.2.4-7509

### Android version

Android 14

### Device

Samsung Galaxy S23

### Other details

Adding that with edit, there is also another problem. "Remember and switch to the last used volume" function doesn't work properly. Even though the last volume is 5 for example, it's stuck at 6 and always opens anime with 6 volume 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [x] I will fill out all of the requested information in this form.

**Comment by LittleFreak** [comment] 2024-03-08 09:54
Does PIP (picture in picture) still work for you, when your issue occurs?

**Comment by KeremDgGG** [comment] 2024-03-08 09:55
> Does PIP (picture in picture) still work for you, when your issue occurs?

It doesn't, just tried

**Comment by LittleFreak** [comment] 2024-03-08 19:40
Then we have both the same issue.
Good news: as annoying as it is, there is a workaround.
You can force stop aniyomi/animiru, clear it's cache and restart the app.

Even so, I'd be happy, when a permanent fix is found ^^

**Comment by fakebhai** [comment] 2024-03-08 19:55
duplicate of #1446 also solution is mentioned there

**Comment by KeremDgGG** [comment] 2024-03-08 19:57
> duplicate of #1446 also solution is mentioned there

It isn't enabled on my phone and still happens

**Comment by fakebhai** [comment] 2024-03-08 20:00
> > duplicate of #1446 also solution is mentioned there
> 
> It isn't enabled on my phone and still happens 

weird, can you try doing horizontal and vertical without going inside the player?

also open different issue for each thing unless it's relevant.

**Comment by abdallahmehiz** [comment] 2024-08-11 11:22
Fixed with 71e0d44a0b82a708342a8b22e108dd051e2c1615

**Closed by abdallahmehiz** 2024-08-11 11:22 UTC
