### ISSUE TITLE
Animyomi manga extension not showing 

### ISSUE THREAD

**Issue by naaec** [aniyomiorg/aniyomi#960] opened 2023-03-31 20:43 UTC
### Steps to reproduce

1: go to browse
2:, go to manga extension
3: Manga extension not showing 

### Expected behavior

Manga extension should show up,
 

### Actual behavior

Only downloaded one's are showing up

### Crash logs

--------- beginning of system
--------- beginning of main
04-01 01:50:56.660  3297  3297 E hiyomi.mi.debu: Unknown bits set in runtime_flags: 0x20000
04-01 01:50:56.668  3297  3297 E hiyomi.mi.debu: Not starting debugger since process cannot load the jdwp agent.
04-01 01:50:57.314  3297  3333 E Perf    : Fail to get file list xyz.jmir.tachiyomi.mi.debug
04-01 01:50:57.314  3297  3333 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
04-01 01:50:57.315  3297  3333 E Perf    : Fail to get file list oat
04-01 01:50:57.315  3297  3333 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
04-01 01:50:58.380  3297  3348 E SQLiteLog: (284) automatic index on C(anime_id)
04-01 01:50:58.380  3297  3348 E SQLiteLog: (284) automatic index on animes_categories(anime_id)
04-01 02:01:24.388  8616  8616 E hiyomi.mi.debu: Unknown bits set in runtime_flags: 0x20000
04-01 02:01:24.396  8616  8616 E hiyomi.mi.debu: Not starting debugger since process cannot load the jdwp agent.
04-01 02:01:25.161  8616  8650 E Perf    : Fail to get file list xyz.jmir.tachiyomi.mi.debug
04-01 02:01:25.161  8616  8650 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
04-01 02:01:25.162  8616  8650 E Perf    : Fail to get file list oat
04-01 02:01:25.162  8616  8650 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
04-01 02:01:26.287  8616  8703 E SQLiteLog: (284) automatic index on C(anime_id)
04-01 02:01:26.287  8616  8703 E SQLiteLog: (284) automatic index on animes_categories(anime_id)
App version: 0.12.3.10-4517 (standard, 05ccfbcc6, 72, 2023-02-09T10:48Z)
Android version: 10 (SDK 29)
Android build ID: QKQ1.191014.001 test-keys
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: olivelite
Device model: Redmi 8A
Device product name: olivelite

### Aniyomi version

0.12.3.10-4517 (standard, 05ccfbcc6, 72, 2023-02-09T10:48Z)

### Android version

Android 10 (SDK 29)

### Device

Redmi 8A dual 3/32

### Other details

No new extension, only downloaded ones

![IMG_20230401_020806](https://user-images.githubusercontent.com/129553491/229225694-08b903e6-6780-4090-ae6d-e63e696d509a.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [x] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jinhxkslan** [comment] 2023-04-02 04:13
I have this same issue mine is a poco x3 pro

**Comment by NoNameDevil666** [comment] 2023-04-04 09:34
I have the same issue 😭 please help

**Comment by Jor-code23** [comment] 2023-04-04 16:11
Same problem mine is a Galaxy A02 Core

**Comment by Jerrriell** [comment] 2023-04-04 16:41
This has been addressed, its gonna be fixed their eis an alternate beta aniyomi made by the same Dev

https://github.com/jmir1/aniyomi-mpv-beta/releases

It has new player too and manga works

**Comment by Helpful-Neko** [comment] 2023-04-04 21:40
Same issue for me to but it won't even show me download ones 😅

**Comment by NoNameDevil666** [comment] 2023-04-04 21:42
> This has been addressed, its gonna be fixed their eis an alternate beta aniyomi made by the same Dev
> 
> https://github.com/jmir1/aniyomi-mpv-beta/releases
> 
> It has new player too and manga works

Thanks bro it works like butter 🧈 🙏👍 thank you very much 👍

**Comment by Helpful-Neko** [comment] 2023-04-04 21:45
> This has been addressed, its gonna be fixed their eis an alternate beta aniyomi made by the same Dev
> 
> https://github.com/jmir1/aniyomi-mpv-beta/releases
> 
> It has new player too and manga works

Thanks I'll give this a try😸

**Comment by Quickdesh** [comment] 2023-06-16 12:11
Duplicate of #844

**Closed by Quickdesh** 2023-06-16 12:11 UTC
