### ISSUE TITLE
Aniyomi for pc/laptop version for linux .

### ISSUE THREAD

**Issue by Pns2051** [aniyomiorg/aniyomi#1843] opened 2024-12-12 17:31 UTC
### Describe your suggested feature

I am not forcing devs to release .But it could be soo much better if it is done.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is a request regarding an extension, I should be opening an issue in the extension's repository.
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-12-12 17:33
Duplicate of #1840

**Closed by Secozzi** 2024-12-12 17:33 UTC
Labels: Feature request

**Comment by abdallahmehiz** [comment] 2024-12-12 17:49
You can try Waydroid 👍

**Comment by Pns2051** [comment] 2024-12-14 12:32
> You can try Waydroid 👍

thnx bud.

**Comment by abdallahmehiz** [comment] 2024-12-18 19:31
> nah, i use [MustardChef/WSABuilds](https://github.com/MustardChef/WSABuilds?rgh-link-date=2024-12-18T19%3A28%3A39Z) as WSA, WSL but Android. [alesimula/wsa_pacman](https://github.com/alesimula/wsa_pacman?rgh-link-date=2024-12-18T19%3A28%3A39Z) is for download apk straight from websites and install

WSA is for windows. OP asked about linux...

**Comment by AdityaJha012** [comment] 2024-12-25 15:02
You can use mangayomi for it.. it has similar features like aniyomi... same interface and everything but for PC.. it is also available on github
