### ISSUE TITLE
Smart TvBox & Android Tv Request

### ISSUE THREAD

**Issue by Neeekoo-Chan** [aniyomiorg/aniyomi#1558] opened 2024-05-01 00:37 UTC
### Describe your suggested feature

I want it to work on Smart TvBox And Make it Compatible to Work On Android Tv In The Latest Version. 12.3.8 is working On Android Tv Compatible But It Can't take the latest extension so can you guys support the latest extension on old version of the app 

### Other details

Support All Extension Repository On 12.3.8 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-08-14 10:46
Duplicate of #162

**Closed by Secozzi** 2024-08-14 10:46 UTC
