### ISSUE TITLE
Show suggestions atleast in mangas

### ISSUE THREAD

**Issue by imDusht** [aniyomiorg/aniyomi#1793] opened 2024-10-13 05:14 UTC
### Describe your suggested feature

Suggestion feature should work like in Komikku client and should show suggestions based on a manga.

![Screenshot_20241013-104127_Komikku](https://github.com/user-attachments/assets/51c4efc7-cd4a-47b5-907b-89d7bea401d8)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is a request regarding an extension, I should be opening an issue in the extension's repository.
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment] 2024-10-25 11:49
Duplicate of #45

**Closed by Secozzi** 2024-10-25 11:49 UTC
Labels: Feature request
