### ISSUE TITLE
Tapzone not working properly 

### ISSUE THREAD

**Issue by Kaustubh18111** [aniyomiorg/aniyomi#1340] opened 2024-01-21 21:50 UTC
### Steps to reproduce

1.open any manga or manhwa 
2.set reading mode to long strips
3tapzone for next won't work while tapzone for previous will be fine 

### Expected behavior

In long strips mode Next tap zone should work it should scroll the page it should work because it worked before recent updates and it works in latest version of tachiyomi 

### Actual behavior

In long strips mode Next tapzone doesn't work while previous one does 

### Aniyomi version

0.15.2.3

### Android version

Android 11

### Device

OnePlus nord CE

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment] 2024-01-21 22:34
Duplicate of #1294

**Closed** 2024-01-21 22:34 UTC
Labels: duplicate
