### ISSUE TITLE
 Manga Source Not Found

### ISSUE THREAD

**Issue by TouchOf** [aniyomiorg/aniyomi#1031] opened 2023-06-15 03:31 UTC
### Steps to reproduce

1.Click on a manga that's already saved in library. 
2.Go to the manga sources. 

### Expected behavior

The respective manga should open or the manga sources should be listed. 

### Actual behavior

The error 'Source not found' comes up and the extensions that were already on the device get removed. 

### Crash logs

![Screenshot_2023-06-15-08-44-06-681_xyz jmir tachiyomi mi-edit](https://github.com/jmir1/aniyomi/assets/136668180/65e4450e-4f49-4ee6-9499-ee1b627c476a)
![Screenshot_2023-06-15-08-43-40-495_xyz jmir tachiyomi mi-edit](https://github.com/jmir1/aniyomi/assets/136668180/d8e715e8-fc68-4633-9e76-9c6a9cae8cd9)
![Screenshot_2023-06-15-08-57-13-927_xyz jmir tachiyomi mi-edit](https://github.com/jmir1/aniyomi/assets/136668180/b5e5e7d1-a6bc-44be-a4cc-84caea049348)

### Aniyomi version

App version: 0.12.3.10 

### Android version

Android 12

### Device

Poco X4 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment] 2023-06-16 12:04
Duplicate of #843

**Closed by Quickdesh** 2023-06-16 12:04 UTC
