### ISSUE TITLE
Manga extension doesn't work.

### ISSUE THREAD

**Issue by AxMh** [aniyomiorg/aniyomi#1038] opened 2023-06-17 08:32 UTC
### Steps to reproduce

1.Open the app
2.Go to manga extension
3.The extension don't show and says "Faild to get the extension list"

### Expected behavior

The extension for manga should show immediately.

### Actual behavior

It remains a blank page 

### Aniyomi version

0.12.3.10

### Android version

Android 12

### Device

Xiaomi 11Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment] 2023-06-18 03:05
Duplicate of #843

**Closed by Quickdesh** 2023-06-18 03:05 UTC

**Comment by Smilingchubby** [comment] 2023-09-25 04:27
Same problem please fix it 🥺
