### ISSUE TITLE
Add cast feature

### ISSUE THREAD

**Issue by jagp8** [aniyomiorg/aniyomi#1295] opened 2024-01-15 12:35 UTC
### Describe your suggested feature

Ad an option to cast the chapters to chromecast or tvs

### Other details

I've seen similar suggestions and the replies were something that we have external players or that it should work in android tv.

The problem with using vlc is that some of the extension (like AnimeFLV and AnimeID right now) ends up giving some error, furthermore I think it should be easier to mantain a feature in the main repo than in 15 different extension.

And the problem with android tv is that some devices like the firsts chromecast doesn't have android tv. But even if they had I don't think people use the tv to read manga, probably most of us use the phone, and it would be easier to have all the libraries just in one device for simplification in addition to backup managing easiness

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.1](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment] 2024-01-15 21:07
duplicate of https://github.com/aniyomiorg/aniyomi/issues/78

**Closed by Quickdesh** 2024-01-15 21:07 UTC
Labels: duplicate
